### PR TITLE
[MNT-24120] log4j1 references translated to log4jv2

### PR DESCRIPTION
**Pull request by pksingh41**
https://alfresco.atlassian.net/browse/MNT-24120
Log4j1 references translated to Log4jv2 in ACS in process SDK

### CODE REVIEW

**Review by kavitshah-gl — COMMENTED** [review]
Did you also look into this Java file?
https://github.com/Alfresco/alfresco-sdk/blob/MNT-24120-Log4j1_references_translated_to_Log4jv2/plugins/alfresco-maven-plugin/src/main/java/org/alfresco/maven/plugin/AbstractRunMojo.java

I see some references of log4j in there, shall we need to upgrade it to log4j2 as well?

**Comment by pksingh41** [comment]
Yes, we have to upgrade it to log4j2 as well !!

**Comment by pksingh41** [comment]
Done

**Review by kavitshah-gl — APPROVED** [review]
Approved

**Review by suneet-gupta — APPROVED** [review]
LGTM

**Pull request merged**
